function ai = cheb_approx(m_cheb, n_cheb, fvals, zk, xk, a, b)
    
% Calculates Chebyshev coefficients for a polynomial of order
% n, using m nodes (generated by cheb_nodes)
% zk are the nodes in (-1, 1)
% xk are the nodes in (a, b)
% These are fed in so that the nodes do not have to be recalculated
% every time we call the approximation

% Chebyshev Polynomials
Tz = zeros(m_cheb, n_cheb + 1)
Tz(:, 1) .= 1.0
Tz(:, 2) = zk
for i in 1:m_cheb
    for j in 3:(n_cheb + 1)
        Tz(i, j) = 2.0 * zk(i) * Tz(i, j - 1) - Tz(i, j - 2)
    end
end

% Coefficients
if m_cheb == (n_cheb + 1)
    ai = Tz \ fvals % if m = n + 1, can solve directly 
else
    ai = (Tz' * Tz) \ Tz' * fvals % otherwise, need least squares
end

    
end